on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

name: Deployment

concurrency: production

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        env:
          SECURE_SECRET: ${{ secrets.MY_SECURE_SECRET }}
        run: |
          echo "Deploying to production: $SECURE_SECRET"
